sonar.projectKey=DanLambe_wdio-puppeteer-video-service
sonar.organization=danlambe

sonar.sources=src,scripts
sonar.tests=tests
sonar.exclusions=build/**,coverage/**,node_modules/**,tests/results/**
sonar.cpd.exclusions=tests/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
